name: RulesUI
main: RulesUI\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

depend:
  - FormAPI

commands:
  rules:
    description: View the server rules
    usage: "/rules"
    permission: rulesui.use

permissions:
  rulesui.use:
    default: true
